---
name: Ansible Galaxy
on:
  workflow_dispatch:
  push:
    paths:
      - "README.md"
    tags:
      - "*"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install test dependencies
        run: pip3 install yamllint

      - name: Run Yamllint
        run: yamllint .

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2404
          - debian12
          - fedora40
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install test dependencies
        run: pip3 install ansible-core molecule molecule-plugins[docker]

      - name: Run Molecule tests
        run: molecule test --all
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_IMAGE: "${{ matrix.distro }}"

  galaxy:
    name: Galaxy
    runs-on: ubuntu-latest
    needs: molecule
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
